using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace YourGamesList.Common;

public interface ICountriesService
{
    string[] GetAllIsoCodes();
    bool ValidateThreeLetterIsoCode(string? isoCode);
    bool ValidateFullEnglishName(string? isoCode);
    bool TryParseFullEnglishName(string fullEnglishName, [NotNullWhen(true)] out string? isoCode);
    bool TryParseThreeLetterIsoRegionName(string isoCode, [NotNullWhen(true)] out string? fullEnglishName);
}

public class CountriesService : ICountriesService
{
    private static readonly string[] IsoCodes =
    [
        "ABW",
        "AFG",
        "AGO",
        "AIA",
        "ALA",
        "ALB",
        "AND",
        "ARE",
        "ARG",
        "ARM",
        "ASM",
        "ATG",
        "AUS",
        "AUT",
        "AZE",
        "BDI",
        "BEL",
        "BEN",
        "BES",
        "BFA",
        "BGD",
        "BGR",
        "BHR",
        "BHS",
        "BIH",
        "BLM",
        "BLR",
        "BLZ",
        "BMU",
        "BOL",
        "BRA",
        "BRB",
        "BRN",
        "BTN",
        "BWA",
        "CAF",
        "CAN",
        "CCK",
        "CHE",
        "CHL",
        "CHN",
        "CIV",
        "CMR",
        "COD",
        "COG",
        "COK",
        "COL",
        "COM",
        "CPV",
        "CRI",
        "CUB",
        "CUW",
        "CXR",
        "CYM",
        "CYP",
        "CZE",
        "DEU",
        "DJI",
        "DMA",
        "DNK",
        "DOM",
        "DZA",
        "ECU",
        "EGY",
        "ERI",
        "ESP",
        "EST",
        "ETH",
        "FIN",
        "FJI",
        "FLK",
        "FRA",
        "FRO",
        "FSM",
        "GAB",
        "GBR",
        "GEO",
        "GGY",
        "GHA",
        "GIB",
        "GIN",
        "GLP",
        "GMB",
        "GNB",
        "GNQ",
        "GRC",
        "GRD",
        "GRL",
        "GTM",
        "GUF",
        "GUM",
        "GUY",
        "HKG",
        "HND",
        "HRV",
        "HTI",
        "HUN",
        "IDN",
        "IMN",
        "IND",
        "IOT",
        "IRL",
        "IRN",
        "IRQ",
        "ISL",
        "ISR",
        "ITA",
        "JAM",
        "JEY",
        "JOR",
        "JPN",
        "KAZ",
        "KEN",
        "KGZ",
        "KHM",
        "KIR",
        "KNA",
        "KOR",
        "KWT",
        "LAO",
        "LBN",
        "LBR",
        "LBY",
        "LCA",
        "LIE",
        "LKA",
        "LSO",
        "LTU",
        "LUX",
        "LVA",
        "MAC",
        "MAF",
        "MAR",
        "MCO",
        "MDA",
        "MDG",
        "MDV",
        "MEX",
        "MHL",
        "MKD",
        "MLI",
        "MLT",
        "MMR",
        "MNE",
        "MNG",
        "MNP",
        "MOZ",
        "MRT",
        "MSR",
        "MTQ",
        "MUS",
        "MWI",
        "MYS",
        "MYT",
        "NAM",
        "NCL",
        "NER",
        "NFK",
        "NGA",
        "NIC",
        "NIU",
        "NLD",
        "NOR",
        "NPL",
        "NRU",
        "NZL",
        "OMN",
        "PAK",
        "PAN",
        "PCN",
        "PER",
        "PHL",
        "PLW",
        "PNG",
        "POL",
        "PRI",
        "PRK",
        "PRT",
        "PRY",
        "PSE",
        "PYF",
        "QAT",
        "REU",
        "ROU",
        "RUS",
        "RWA",
        "SAU",
        "SDN",
        "SEN",
        "SGP",
        "SHN",
        "SJM",
        "SLB",
        "SLE",
        "SLV",
        "SMR",
        "SOM",
        "SPM",
        "SRB",
        "SSD",
        "STP",
        "SUR",
        "SVK",
        "SVN",
        "SWE",
        "SWZ",
        "SXM",
        "SYC",
        "SYR",
        "TCA",
        "TCD",
        "TGO",
        "THA",
        "TJK",
        "TKL",
        "TKM",
        "TLS",
        "TON",
        "TTO",
        "TUN",
        "TUR",
        "TUV",
        "TWN",
        "TZA",
        "UGA",
        "UKR",
        "UMI",
        "URY",
        "USA",
        "UZB",
        "VAT",
        "VCT",
        "VEN",
        "VGB",
        "VIR",
        "VNM",
        "VUT",
        "WLF",
        "WSM",
        "XKK",
        "YEM",
        "ZAF",
        "ZMB",
        "ZWE"
    ];

    private static readonly string[] FullEnglishNames =
    [
        "Aruba",
        "Afghanistan",
        "Angola",
        "Anguilla",
        "Åland Islands",
        "Albania",
        "Andorra",
        "United Arab Emirates",
        "Argentina",
        "Armenia",
        "American Samoa",
        "Antigua & Barbuda",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Burundi",
        "Belgium",
        "Benin",
        "Bonaire, Sint Eustatius and Saba",
        "Burkina Faso",
        "Bangladesh",
        "Bulgaria",
        "Bahrain",
        "Bahamas",
        "Bosnia & Herzegovina",
        "St. Barthélemy",
        "Belarus",
        "Belize",
        "Bermuda",
        "Bolivia",
        "Brazil",
        "Barbados",
        "Brunei",
        "Bhutan",
        "Botswana",
        "Central African Republic",
        "Canada",
        "Cocos (Keeling) Islands",
        "Switzerland",
        "Chile",
        "China",
        "Côte d'Ivoire",
        "Cameroon",
        "Congo (DRC)",
        "Congo",
        "Cook Islands",
        "Colombia",
        "Comoros",
        "Cabo Verde",
        "Costa Rica",
        "Cuba",
        "Curaçao",
        "Christmas Island",
        "Cayman Islands",
        "Cyprus",
        "Czechia",
        "Germany",
        "Djibouti",
        "Dominica",
        "Denmark",
        "Dominican Republic",
        "Algeria",
        "Ecuador",
        "Egypt",
        "Eritrea",
        "Spain",
        "Estonia",
        "Ethiopia",
        "Finland",
        "Fiji",
        "Falkland Islands",
        "France",
        "Faroe Islands",
        "Micronesia",
        "Gabon",
        "United Kingdom",
        "Georgia",
        "Guernsey",
        "Ghana",
        "Gibraltar",
        "Guinea",
        "Guadeloupe",
        "Gambia",
        "Guinea-Bissau",
        "Equatorial Guinea",
        "Greece",
        "Grenada",
        "Greenland",
        "Guatemala",
        "French Guiana",
        "Guam",
        "Guyana",
        "Hong Kong SAR",
        "Honduras",
        "Croatia",
        "Haiti",
        "Hungary",
        "Indonesia",
        "Isle of Man",
        "India",
        "British Indian Ocean Territory",
        "Ireland",
        "Iran",
        "Iraq",
        "Iceland",
        "Israel",
        "Italy",
        "Jamaica",
        "Jersey",
        "Jordan",
        "Japan",
        "Kazakhstan",
        "Kenya",
        "Kyrgyzstan",
        "Cambodia",
        "Kiribati",
        "St. Kitts & Nevis",
        "Korea",
        "Kuwait",
        "Laos",
        "Lebanon",
        "Liberia",
        "Libya",
        "St. Lucia",
        "Liechtenstein",
        "Sri Lanka",
        "Lesotho",
        "Lithuania",
        "Luxembourg",
        "Latvia",
        "Macao SAR",
        "St. Martin",
        "Morocco",
        "Monaco",
        "Moldova",
        "Madagascar",
        "Maldives",
        "Mexico",
        "Marshall Islands",
        "North Macedonia",
        "Mali",
        "Malta",
        "Myanmar",
        "Montenegro",
        "Mongolia",
        "Northern Mariana Islands",
        "Mozambique",
        "Mauritania",
        "Montserrat",
        "Martinique",
        "Mauritius",
        "Malawi",
        "Malaysia",
        "Mayotte",
        "Namibia",
        "New Caledonia",
        "Niger",
        "Norfolk Island",
        "Nigeria",
        "Nicaragua",
        "Niue",
        "Netherlands",
        "Norway",
        "Nepal",
        "Nauru",
        "New Zealand",
        "Oman",
        "Pakistan",
        "Panama",
        "Pitcairn Islands",
        "Peru",
        "Philippines",
        "Palau",
        "Papua New Guinea",
        "Poland",
        "Puerto Rico",
        "North Korea",
        "Portugal",
        "Paraguay",
        "Palestinian Authority",
        "French Polynesia",
        "Qatar",
        "Réunion",
        "Romania",
        "Russia",
        "Rwanda",
        "Saudi Arabia",
        "Sudan",
        "Senegal",
        "Singapore",
        "St Helena, Ascension, Tristan da Cunha",
        "Svalbard & Jan Mayen",
        "Solomon Islands",
        "Sierra Leone",
        "El Salvador",
        "San Marino",
        "Somalia",
        "St. Pierre & Miquelon",
        "Serbia",
        "South Sudan",
        "Sao Tomé & Príncipe",
        "Suriname",
        "Slovakia",
        "Slovenia",
        "Sweden",
        "Eswatini",
        "Sint Maarten",
        "Seychelles",
        "Syria",
        "Turks & Caicos Islands",
        "Chad",
        "Togo",
        "Thailand",
        "Tajikistan",
        "Tokelau",
        "Turkmenistan",
        "Timor-Leste",
        "Tonga",
        "Trinidad & Tobago",
        "Tunisia",
        "Türkiye",
        "Tuvalu",
        "Taiwan",
        "Tanzania",
        "Uganda",
        "Ukraine",
        "U.S. Outlying Islands",
        "Uruguay",
        "United States",
        "Uzbekistan",
        "Vatican City",
        "St. Vincent & Grenadines",
        "Venezuela",
        "British Virgin Islands",
        "U.S. Virgin Islands",
        "Vietnam",
        "Vanuatu",
        "Wallis & Futuna",
        "Samoa",
        "Kosovo",
        "Yemen",
        "South Africa",
        "Zambia",
        "Zimbabwe",
    ];

    private static readonly HashSet<string> ThreeLetterIsoSet;
    private static readonly HashSet<string> FullEnglishNamesSet;

    private static readonly Dictionary<string, string> IsoCodeToFullNameMap;
    private static readonly Dictionary<string, string> FullNameToIsoCodeMap;

    static CountriesService()
    {
        ThreeLetterIsoSet = new HashSet<string>(IsoCodes, StringComparer.OrdinalIgnoreCase);
        FullEnglishNamesSet = new HashSet<string>(FullEnglishNames, StringComparer.OrdinalIgnoreCase);

        IsoCodeToFullNameMap = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        FullNameToIsoCodeMap = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        for (var i = 0; i < IsoCodes.Length; i++)
        {
            var isoCode = IsoCodes[i];
            var fullName = FullEnglishNames[i];

            IsoCodeToFullNameMap[isoCode] = fullName;
            FullNameToIsoCodeMap[fullName] = isoCode;
        }
    }

    public string[] GetAllIsoCodes()
    {
        return IsoCodes;
    }

    public bool ValidateThreeLetterIsoCode(string? isoCode)
    {
        if (string.IsNullOrWhiteSpace(isoCode))
        {
            return false;
        }

        return ThreeLetterIsoSet.Contains(isoCode);
    }

    public bool ValidateFullEnglishName(string? isoCode)
    {
        if (string.IsNullOrWhiteSpace(isoCode))
        {
            return false;
        }

        return FullEnglishNamesSet.Contains(isoCode);
    }

    public bool TryParseFullEnglishName(string fullEnglishName, [NotNullWhen(true)] out string? isoCode)
    {
        if (string.IsNullOrWhiteSpace(fullEnglishName))
        {
            isoCode = null;
            return false;
        }

        return FullNameToIsoCodeMap.TryGetValue(fullEnglishName.Trim(), out isoCode);
    }

    public bool TryParseThreeLetterIsoRegionName(string isoCode, [NotNullWhen(true)] out string? fullEnglishName)
    {
        if (string.IsNullOrWhiteSpace(isoCode))
        {
            fullEnglishName = null;
            return false;
        }

        return IsoCodeToFullNameMap.TryGetValue(isoCode.Trim(), out fullEnglishName);
    }
}